console.log("---Step 1---");
console.log("---WAP To Swap Two Variable Using Third Variable---");
var sweety="Sweety";
var cutie="Cutie";
console.log("-----Before Swapping-----");
console.log("sweety::",sweety,"cutie::",cutie);
console.log("----- After Swapping-----");
var temp;
temp=sweety;
sweety=cutie;
cutie=temp;
console.log("sweety::",sweety,"cutie::",cutie);
console.log("---Step 2---");
console.log("---WAP To Swap Three Variable Using Third Variable---");
var n1=100;
var n2=200;
var n3=300;
console.log("-----Before Swapping-----");
console.log("n1::",n1,"n2::",n2,"n3::",n3);
console.log("----- After Swapping-----");

var temp;
temp=n1;
n1=n2;
n2=n3;
n3=temp;
console.log("n1::",n1,"n2::",n2,"n3::",n3);
