console.log("---Step 1---");
var fullName; 
console.log("Full Name variable value before Initialization:", fullName);
fullName="Yogita Pore";
console.log("Full Name variable value after Initialization:", fullName);
fullName="Yogita N.Pore";
console.log("Full Name variable value after Updation:", fullName);
console.log("---Step 2---");
var myLove="I Love Only JS";
console.log("myLove");
console.log("---Step 3---");
var firstName="Yogita";
var lastName="Pore";
var age=24;
var address="Pune";
var pincode="411 011";
var gender="Female";
var isMarried="Yes";
console.log("First Name:",firstName);console.log("Last Name:",lastName);
console.log("Age:",age);
console.log("Address:",address);
console.log("Pincode:",pincode);
console.log("Gender:",gender);

console.log("Married/Unmarried :",isMarried);