var num=5;
console.log("num=",num);
var a=num++;
console.log("postfix",a);
console.log("num=",num);
var b=++num;
console.log("prefix=",b);
console.log("num=",num);
// console.log("------------------");
// var n1=5;
// var result= n1++ + ++n1 + n1++;
// console.log(result);
// console.log(n1);
// console.log("------------------");
// var a=2;
// var b= ++a + ++a + a++ - --a;
// console.log(b);
// console.log(a);
// console.log("------------------");
// var a=4;
// var b= a-- + ++a + ++a + a++;
// console.log(b);
// console.log(a);

